command:
  - node
  - dist/server/index.js

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse-id
  - name: DATABRICKS_GENIE_SPACE_ID
    valueFrom: genie-space-id
  - name: DATABRICKS_SERVING_ENDPOINT_NAME
    value: databricks-gpt-5-2
